name: Tamil News Automation

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 2,8,14,20 * * *'  # 7:30am, 1:30pm, 7:30pm, 1:30am IST

jobs:
  run-news-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tamil News Main Script
        run: python main.py